# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace        # Trims trailing whitespace
    -   id: end-of-file-fixer          # Ensures that a file is either empty or ends with one newline
    -   id: check-yaml                 # Checks YAML files for parseable syntax
    -   id: check-added-large-files    # Prevents giant files from being committed
    -   id: debug-statements           # Checks for debugger imports and breakpoints calls
    -   id: double-quote-string-fixer  # Replaces double quoted strings with single quoted strings
    -   id: fix-encoding-pragma        # Adds # -*- coding: utf-8 -*- to the top of python files
-   repo: https://github.com/hhatto/autopep8
    rev: v2.1.0
    hooks:
    -   id: autopep8  # Ensures PEP 8 compliance
-   repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
    -   id: isort  # Sorts imports
        # See https://pycqa.github.io/isort/docs/configuration/multi_line_output_modes.html
        args: [--multi-line=5, --line-length=127]
-   repo: https://github.com/PyCQA/autoflake
    rev: v2.3.1
    hooks:
    -   id: autoflake  # Removes unused imports and variables
        args: [--in-place, --recursive, --remove-all-unused-imports, --remove-unused-variables]
